on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

name: CI Tests

jobs:
  check_and_test:
    name: Check
    strategy:
      fail-fast: false
      matrix:
        target: [mysql, mariadb]
        os: [
          ubuntu-latest,
          ubuntu-24.04-arm,
          macos-15-intel,
          macos-15,
          windows-2025,
        ]
        features: [default, buildtime_bindgen, bundled, bundled_with_system_openssl]
        include:
          - target: mysql
            os: windows-2025
            install: vcpkg
            features: buildtime_bindgen
          - target: mariadb
            os: windows-202
            install: vcpkg
            features: buildtime_bindgen
        exclude:
          # Bundled builds never use MariaDB target
          - target: mariadb
            features: bundled
          - target: mariadb
            features: bundled_with_system_openssl
          # Building feature `bundled_with_system_openssl` isn't useful on Windows hosts
          - os: windows-2025
            features: bundled_with_system_openssl

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Set environment variables
        shell: bash
        run: |
          echo "RUSTFLAGS=-D warnings" >> $GITHUB_ENV
          echo "RUSTDOCFLAGS=-D warnings" >> $GITHUB_ENV

      - name: Stop current MySQL server
        if: ${{ runner.os == 'Linux' && matrix.target == 'mariadb' }}
        shell: bash
        run: |
          sudo systemctl stop mysql.service
          sudo apt-get purge -y mysql-server

      - name: Install MySQL (Linux)
        if: ${{ runner.os == 'Linux' && matrix.target == 'mysql' && !startsWith(matrix.features, 'bundled') }}
        shell: bash
        run: |
          sudo systemctl start mysql.service
          sudo apt-get update
          sudo apt-get -y install libmysqlclient-dev

      - name: Install dependencies (Linux)
        if: ${{ runner.os == 'Linux' && startsWith(matrix.features, 'bundled') }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install libtirpc-dev

      - name: Install MariaDB Client Libs and Server (Linux)
        if: ${{ runner.os == 'Linux' && matrix.target == 'mariadb' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install libmariadb-dev mariadb-server
          sleep 3
          sudo mysql -e 'set password=password("root")'

      - name: Linux env
        if: ${{ runner.os == 'Linux' && !startsWith(matrix.features, 'bundled') }}
        shell: bash
        run: |
          sudo systemctl start mysql.service
          mysql -e "create database diesel_test; create database diesel_unit_test; grant all on \`diesel_%\`.* to 'root'@'localhost';" -uroot -proot
          echo "MYSQL_DATABASE_URL=mysql://root:root@localhost/diesel_test" >> $GITHUB_ENV
          echo "MYSQL_EXAMPLE_DATABASE_URL=mysql://root:root@localhost/diesel_example" >> $GITHUB_ENV
          echo "MYSQL_UNIT_TEST_DATABASE_URL=mysql://root:root@localhost/diesel_unit_test" >> $GITHUB_ENV

      - name: Install MySQL (MacOS Intel)
        if: ${{ matrix.os == 'macos-15-intel' && matrix.target == 'mysql' && !startsWith(matrix.features, 'bundled') }}
        run: |
          brew update
          brew install mysql@8.0
          brew services start mysql@8.0
          sleep 3
          /usr/local/opt/mysql@8.0/bin/mysql -e "create database diesel_test; create database diesel_unit_test;"
          /usr/local/opt/mysql@8.0/bin/mysql -e "create user runner@localhost; grant all on \`diesel_%\`.* to 'runner'@'localhost';"
          echo "PKG_CONFIG_PATH=/usr/local/opt/mysql@8.0/lib/pkgconfig" >> $GITHUB_ENV
          ls /usr/local/opt/mysql@8.0/include/mysql

      - name: Install MariaDB 10.5 (MacOS Intel)
        if: ${{ matrix.os == 'macos-15-intel' && matrix.target == 'mariadb' }}
        run: |
          brew install mariadb@10.6
          echo "PKG_CONFIG_PATH=/usr/local/opt/mariadb@10.6/lib/pkgconfig" >> $GITHUB_ENV

      - name: Install MySQL (MacOS M1)
        if: ${{ matrix.os == 'macos-15' && matrix.target == 'mysql' && !startsWith(matrix.features, 'bundled') }}
        run: |
          brew update
          brew install mysql@8.4
          brew services start mysql@8.4
          sleep 3
          /opt/homebrew/opt/mysql@8.4/bin/mysql -e "create database diesel_test; create database diesel_unit_test;"
          /opt/homebrew/opt/mysql@8.4/bin/mysql -e "create user runner@localhost; grant all on \`diesel_%\`.* to 'runner'@'localhost';"
          echo "MYSQLCLIENT_LIB_DIR=/opt/homebrew/opt/mysql@8.4/lib" >> $GITHUB_ENV
          echo "MYSQLCLIENT_INCLUDE_DIR=/opt/homebrew/opt/mysql@8.4/include/mysql" >> $GITHUB_ENV
          echo "MYSQLCLIENT_VERSION=8.4" >> $GITHUB_ENV

      - name: Install MariaDB latest (MacOS M1)
        if: ${{ matrix.os == 'macos-15' && matrix.target == 'mariadb' }}
        run: |
          brew update
          brew install mariadb@11.4
          ls /opt/homebrew/opt/mariadb@11.4/lib/pkgconfig
          sleep 3
          echo "MYSQLCLIENT_LIB_DIR=/opt/homebrew/opt/mariadb@11.4/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/homebrew/opt/mariadb@11.4/lib/pkgconfig" >> $GITHUB_ENV

      - name: Env MacOS
        if: (matrix.os == 'macos-15-intel' || matrix.os == 'macos-15') && !startsWith(matrix.features, 'bundled')
        run: |
          echo "MYSQL_DATABASE_URL=mysql://runner@localhost/diesel_test" >> $GITHUB_ENV
          echo "MYSQL_EXAMPLE_DATABASE_URL=mysql://runner@localhost/diesel_example" >> $GITHUB_ENV
          echo "MYSQL_UNIT_TEST_DATABASE_URL=mysql://runner@localhost/diesel_unit_test" >> $GITHUB_ENV

      - name: Install MySQL (Windows)
        if: ${{ runner.os == 'Windows' && matrix.target == 'mysql' && !startsWith(matrix.features, 'bundled') }}
        shell: cmd
        run: |
          curl -L https://dev.mysql.com/get/Downloads/MySQL-8.4/mysql-8.4.0-winx64.zip -o library.zip
          unzip library.zip

      - name: Install MariaDB (Windows)
        if: ${{ runner.os == 'Windows' && matrix.target == 'mariadb' }}
        shell: cmd
        run: |
          curl -L https://archive.mariadb.org/mariadb-11.5.2/winx64-packages/mariadb-11.5.2-winx64.zip -o library.zip
          unzip library.zip

      - name: Set variables for mysql (Windows)
        if: ${{ runner.os == 'Windows' && matrix.target == 'mysql' && !startsWith(matrix.features, 'bundled') }}
        shell: bash
        run: |
          echo "MYSQLCLIENT_LIB_DIR=${{github.workspace}}/mysql-8.4.0-winx64/lib/" >> $GITHUB_ENV
          echo "MYSQLCLIENT_VERSION=8.4.0" >> $GITHUB_ENV
          echo "MYSQLCLIENT_INCLUDE_DIR=${{github.workspace}}/mysql-8.4.0-winx64/include" >> $GITHUB_ENV
          dir ./mysql-8.4.0-winx64/lib
          dir ./mysql-8.4.0-winx64/include

      - name: Set variables for MariaDB (Windows)
        if: ${{ runner.os == 'Windows' && matrix.target == 'mariadb' }}
        shell: bash
        run: |
          echo "MYSQLCLIENT_LIB_DIR=${{github.workspace}}/mariadb-11.5.2-winx64/lib/" >> $GITHUB_ENV
          echo "MYSQLCLIENT_INCLUDE_DIR=${{github.workspace}}/mariadb-11.5.2-winx64/include/mysql/" >> $GITHUB_ENV
          echo "MYSQLCLIENT_VERSION=11.5.2" >> $GITHUB_ENV
          echo "MYSQLCLIENT_LIBNAME=mariadbclient" >> $GITHUB_ENV
          dir ./mariadb-11.5.2-winx64/lib
          dir ./mariadb-11.5.2-winx64/include

      - name: Windows setup (bundled)
        if: ${{ runner.os == 'Windows' && startsWith(matrix.features, 'bundled') }}
        shell: bash
        run: |
          echo "OPENSSL_RUST_USE_NASM=0" >> $GITHUB_ENV
          echo OPENSSL_SRC_PERL=C:/Strawberry/perl/bin/perl >> $GITHUB_ENV

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check
        shell: bash
        run: |
          cargo check --no-default-features --features "${{ matrix.features }}" "${{ matrix.openssl }}" --verbose

      - name: Tests
        shell: bash
        run: |
          cargo test --no-default-features --features "${{ matrix.features }}" "${{ matrix.openssl }}"

      - name: Test compile diesel
        shell: bash
        # allow to fail as diesel might not pull in the right feature yet
        continue-on-error: true
        run: |
          cargo new test_diesel
          cd test_diesel
          echo "[workspace]" >> Cargo.toml
          cargo add diesel --no-default-features --features "mysql" --git "https://github.com/diesel-rs/diesel/" --branch "main"
          cargo add mysqlclient-sys
          echo "[patch.crates-io]" >> Cargo.toml
          echo "mysqlclient-sys = { path = \"..\" }" >> Cargo.toml
          echo "openssl-sys = { version = \"0.9.93\" }"
          cat Cargo.toml
          echo "use diesel::prelude::*;" > src/main.rs
          echo "fn main() { MysqlConnection::establish(\"foo\").unwrap(); }" >> src/main.rs
          cargo build --features "mysqlclient-sys/${{ matrix.features }}" "${{ matrix.openssl }}"

      - name: Generated bindings.rs
        if: ${{ matrix.os != 'Windows' && !startsWith(matrix.features, 'bundled') }}
        shell: bash
        run: |
          find . -name bindings.rs -ls -exec cat {} \;

      - name: Test all files included
        shell: bash
        if: ${{ matrix.features == 'bundled' }}
        run: |
          rm -rf test_diesel
          git reset --hard HEAD
          cd mysqlclient-src
          cargo package "${{ matrix.openssl }}" 
